http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Açúcar" calories=406.00 proteins=0.00 lipids=0.00 carbohydrates=104.00 measure_amount=7 measure_type="colheres de sopa" food_group="Açúcar" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Açúcar de coco" calories=373.00 proteins=0.00 lipids=0.00 carbohydrates=105.00 measure_amount=20 measure_type="colheres de chá" food_group="Açúcar" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Açúcar demerara" calories=400.00 proteins=0.00 lipids=0.00 carbohydrates=100.00 measure_amount=20 measure_type="colheres de chá" food_group="Açúcar" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Açúcar mascavo" calories=400.00 proteins=0.00 lipids=0.00 carbohydrates=100.00 measure_amount=20 measure_type="colheres de chá" food_group="Açúcar" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Ameixa Seca" calories=240.00 proteins=2.20 lipids=0.38 carbohydrates=63.00 measure_amount=17 measure_type="unidades" food_group="Frutas desidratadas" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Damasco" calories=355.00 proteins=5.00 lipids=0.55 carbohydrates=81.90 measure_amount=11 measure_type="unidades" food_group="Frutas desidratadas" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Banana Desidratada" calories=162.00 proteins=3.00 lipids=0.00 carbohydrates=40.00 measure_amount=18 measure_type="unidades" food_group="Frutas desidratadas" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Tamara" calories=314.00 proteins=2.50 lipids=0.50 carbohydrates=75.00 measure_amount=15 measure_type="unidades" food_group="Frutas desidratadas" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Uva passa" calories=315.00 proteins=3.00 lipids=0.50 carbohydrates=75.00 measure_amount=5 measure_type="colheres de sopa" food_group="Frutas desidratadas" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Psyllium" calories=374.00 proteins=6.00 lipids=2.00 carbohydrates=83.00 measure_amount=16 measure_type="colheres de sopa" food_group="Fibras e sementes" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Semente de chia" calories=486.00 proteins=17.00 lipids=31.00 carbohydrates=42.00 measure_amount=8 measure_type="colheres de sopa" food_group="Fibras e sementes" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Semente de linhaça" calories=534.00 proteins=18.30 lipids=42.16 carbohydrates=28.90 measure_amount=8 measure_type="colheres de sopa" food_group="Fibras e sementes" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Farinha de banana verde" calories=260.00 proteins=1.50 lipids=0.00 carbohydrates=14.00 measure_amount=10 measure_type="colheres de sopa" food_group="Fibras e sementes" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Semente de girassol" calories=584.00 proteins=20.00 lipids=51.00 carbohydrates=21.00 measure_amount=9 measure_type="colheres de sopa" food_group="Fibras e sementes" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Farelo de aveia" calories=389.00 proteins=17.00 lipids=7.00 carbohydrates=66.00 measure_amount=10 measure_type="Colher de soopa" food_group="Fibras e sementes" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Semente de abóbora" calories=540.00 proteins=21.60 lipids=33.60 carbohydrates=12.00 measure_amount=8 measure_type="colheres de sopa" food_group="Fibras e sementes" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Amaranto em flocos" calories=336.00 proteins=12.10 lipids=6.20 carbohydrates=58.00 measure_amount=5 measure_type="colheres de sopa" food_group="Cereais  pães e massas" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Arroz integral" calories=124.00 proteins=2.60 lipids=1.00 carbohydrates=25.80 measure_amount=5 measure_type="colheres de sopa" food_group="Cereais  pães e massas" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Arroz Branco" calories=128.00 proteins=2.50 lipids=0.20 carbohydrates=28.10 measure_amount=5 measure_type="colheres de sopa" food_group="Cereais  pães e massas" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Arroz parboilizado" calories=123.00 proteins=2.90 lipids=0.40 carbohydrates=26.10 measure_amount=5 measure_type="colheres de sopa" food_group="Cereais  pães e massas" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Aveia em flocos grossos" calories=336.00 proteins=15.00 lipids=6.30 carbohydrates=53.00 measure_amount=7 measure_type="colheres de sopa" food_group="Cereais  pães e massas" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Granola Tradicional - Mãe terra" calories=487.00 proteins=10.50 lipids=16.75 carbohydrates=72.00 measure_amount=4 measure_type="colheres de sopa" food_group="Cereais  pães e massas" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Macarrão" calories=125.70 proteins=4.30 lipids=1.00 carbohydrates=24.75 measure_amount=4 measure_type="colheres de sopa" food_group="Cereais  pães e massas" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Macarrão Integral" calories=146.00 proteins=12.00 lipids=1.75 carbohydrates=29.40 measure_amount=4 measure_type="colheres de sopa" food_group="Cereais  pães e massas" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Macarrão (de milho sem glúten)" calories=177.00 proteins=2.60 lipids=2.60 carbohydrates=31.00 measure_amount=4 measure_type="colheres de sopa" food_group="Cereais  pães e massas" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Pão sem glúten" calories=254.10 proteins=6.60 lipids=3.96 carbohydrates=49.50 measure_amount=3 measure_type="fatias" food_group="Cereais  pães e massas" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Pão 100% Integral" calories=230.00 proteins=13.60 lipids=3.20 carbohydrates=36.00 measure_amount=4 measure_type="fatias" food_group="Cereais  pães e massas" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Pão Integral" calories=266.00 proteins=10.10 lipids=6.40 carbohydrates=40.00 measure_amount=4 measure_type="fatias" food_group="Cereais  pães e massas" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Pão Caseiro" calories=252.00 proteins=9.00 lipids=1.80 carbohydrates=50.00 measure_amount=4 measure_type="fatias" food_group="Cereais  pães e massas" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Bolacha de Arroz Pequena" calories=389.40 proteins=8.91 lipids=6.60 carbohydrates=72.60 measure_amount=43 measure_type="bolachas" food_group="Cereais  pães e massas" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Bolacha de Arroz Grande" calories=386.10 proteins=8.91 lipids=6.60 carbohydrates=72.60 measure_amount=8 measure_type="biscoitos" food_group="Cereais  pães e massas" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Quinoa cozida" calories=117.00 proteins=4.48 lipids=6.44 carbohydrates=21.00 measure_amount=4 measure_type="colheres de sopa" food_group="Cereais  pães e massas" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Abacaxi" calories=48.00 proteins=0.90 lipids=0.10 carbohydrates=12.30 measure_amount=1 measure_type="fatia pequena" food_group="Frutas" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Suco de uva integral" calories=130.00 proteins=0.00 lipids=0.00 carbohydrates=32.00 measure_amount=1 measure_type="200mL" food_group="Frutas" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Água de coco" calories=41.00 proteins=0.00 lipids=0.00 carbohydrates=10.00 measure_amount=1 measure_type="200mL" food_group="Frutas" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Ameixa" calories=53.00 proteins=0.80 lipids=0.00 carbohydrates=13.90 measure_amount=1 measure_type="und" food_group="Frutas" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Banana" calories=77.00 proteins=1.20 lipids=0.10 carbohydrates=20.30 measure_amount=1 measure_type="und" food_group="Frutas" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Goiaba" calories=72.10 proteins=1.30 lipids=0.50 carbohydrates=15.60 measure_amount=1 measure_type="und" food_group="Frutas" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Laranja Baia" calories=45.00 proteins=1.00 lipids=0.10 carbohydrates=11.50 measure_amount=1 measure_type="und" food_group="Frutas" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Laranja Pera" calories=37.00 proteins=1.00 lipids=0.10 carbohydrates=8.90 measure_amount=1 measure_type="und" food_group="Frutas" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Maçã" calories=56.00 proteins=0.30 lipids=0.00 carbohydrates=15.20 measure_amount=1 measure_type="und" food_group="Frutas" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Mamão Formosa" calories=45.00 proteins=0.80 lipids=0.10 carbohydrates=11.60 measure_amount=1 measure_type="fatia" food_group="Frutas" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Mamão Papaia" calories=40.00 proteins=0.50 lipids=0.10 carbohydrates=10.40 measure_amount=1 measure_type="fatia" food_group="Frutas" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Manga Palmer" calories=72.00 proteins=0.40 lipids=0.30 carbohydrates=19.40 measure_amount=1 measure_type="und pequena" food_group="Frutas" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Melancia" calories=33.00 proteins=0.90 lipids=0.00 carbohydrates=8.10 measure_amount=1 measure_type="fatia" food_group="Frutas" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Mexerica" calories=58.00 proteins=0.90 lipids=0.10 carbohydrates=14.90 measure_amount=1 measure_type="und" food_group="Frutas" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Pera" calories=61.00 proteins=0.20 lipids=0.20 carbohydrates=16.10 measure_amount=1 measure_type="und" food_group="Frutas" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Uva" calories=53.00 proteins=0.70 lipids=0.20 carbohydrates=13.60 measure_amount=8 measure_type="und" food_group="Frutas" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Abacate" calories=96.00 proteins=1.20 lipids=8.40 carbohydrates=6.00 measure_amount=4 measure_type="colheres de sopa" food_group="Frutas" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Kiwi" calories=51.00 proteins=1.30 lipids=0.60 carbohydrates=11.50 measure_amount=1 measure_type="und" food_group="Frutas" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Melão" calories=29.00 proteins=0.70 lipids=0.00 carbohydrates=7.50 measure_amount=1 measure_type="fatia" food_group="Frutas" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Morango" calories=30.00 proteins=0.90 lipids=0.30 carbohydrates=6.80 measure_amount=10 measure_type="und" food_group="Frutas" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Nibs de cacau" calories=635.00 proteins=13.50 lipids=46.50 carbohydrates=33.50 measure_amount=20 measure_type="colheres de chá" food_group="Frutas" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Coco" calories=434.00 proteins=3.70 lipids=42.00 carbohydrates=10.40 measure_amount=4 measure_type="palmo" food_group="Frutas" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Coco em flocos sem açúcar" calories=737.00 proteins=5.50 lipids=63.00 carbohydrates=36.85 measure_amount=10 measure_type="colheres de sopa" food_group="Frutas" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Milho" calories=138.00 proteins=6.60 lipids=0.60 carbohydrates=28.60 measure_amount=3 measure_type="Colher de sopa" food_group="Cereais  pães e massas" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Tapioca" calories=240.00 proteins=3.20 lipids=0.00 carbohydrates=54.00 measure_amount=5 measure_type="Colher de sopa" food_group="Tuberculos e derivados" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Azeite de oliva" calories=884.00 proteins=0.00 lipids=100.00 carbohydrates=0.00 measure_amount=8 measure_type="Colher de sopa" food_group="Gorduras (de adição)" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Manteiga" calories=726.00 proteins=0.00 lipids=84.40 carbohydrates=0.00 measure_amount=15 measure_type="Colher de chá" food_group="Gorduras (de adição)" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Óleo de coco" calories=821.00 proteins=0.00 lipids=95.20 carbohydrates=0.00 measure_amount=7 measure_type="Colher de sopa" food_group="Gorduras (de adição)" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Banha de porco" calories=902.00 proteins=0.00 lipids=100.00 carbohydrates=0.00 measure_amount=7 measure_type="Colher de sopa" food_group="Gorduras (de adição)" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Azeitona" calories=194.00 proteins=1.20 lipids=20.30 carbohydrates=5.50 measure_amount=26 measure_type="und" food_group="Gorduras/Oleaginosas" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Leite de Coco" calories=166.00 proteins=1.00 lipids=18.40 carbohydrates=2.20 measure_amount=1 measure_type="xícara" food_group="Gorduras/Oleaginosas" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Avelã" calories=707.00 proteins=14.10 lipids=63.00 carbohydrates=17.50 measure_amount=100 measure_type="unidades" food_group="Oleaginosas" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Amendoim" calories=550.00 proteins=19.00 lipids=46.00 carbohydrates=16.00 measure_amount=5 measure_type="colher de sopa" food_group="Oleaginosas" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Pasta de amendoim" calories=588.00 proteins=25.00 lipids=50.00 carbohydrates=20.00 measure_amount=6 measure_type="colher de sopa" food_group="Oleaginosas" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Amendoa" calories=520.00 proteins=16.00 lipids=40.00 carbohydrates=25.00 measure_amount=40 measure_type="und" food_group="Oleaginosas" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Castanha de caju" calories=605.00 proteins=19.00 lipids=49.00 carbohydrates=29.50 measure_amount=25 measure_type="und" food_group="Oleaginosas" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Castanha do Pará" calories=643.00 proteins=14.30 lipids=63.50 carbohydrates=15.10 measure_amount=10 measure_type="und" food_group="Oleaginosas" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Noz" calories=620.00 proteins=14.00 lipids=59.40 carbohydrates=18.40 measure_amount=20 measure_type="und" food_group="Oleaginosas" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Macadamia" calories=702.00 proteins=8.30 lipids=73.70 carbohydrates=13.70 measure_amount=41 measure_type="und" food_group="Oleaginosas" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Pistache" calories=617.00 proteins=20.60 lipids=48.40 carbohydrates=24.80 measure_amount=81 measure_type="und" food_group="Oleaginosas" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Ervilha" calories=88.00 proteins=7.50 lipids=0.50 carbohydrates=15.00 measure_amount=7 measure_type="colhees de sopa" food_group="Leguminosas" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Feijão Carioca" calories=76.00 proteins=4.80 lipids=0.50 carbohydrates=15.00 measure_amount=5 measure_type="colheres de sopa" food_group="Leguminosas" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Feijão Preto" calories=77.00 proteins=4.50 lipids=0.50 carbohydrates=15.00 measure_amount=4 measure_type="colheres de sopa" food_group="Leguminosas" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Grão de bico" calories=355.00 proteins=21.20 lipids=5.40 carbohydrates=15.00 measure_amount=7 measure_type="colheres de sopa" food_group="Leguminosas" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Lentilha" calories=76.30 proteins=6.30 lipids=0.50 carbohydrates=16.30 measure_amount=6 measure_type="colheres de sopa" food_group="Leguminosas" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Atum em óleo" calories=166.00 proteins=26.20 lipids=0.90 carbohydrates=0.00 measure_amount=1 measure_type="lata" food_group="Proteína" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Pescada" calories=107.00 proteins=16.70 lipids=4.00 carbohydrates=0.00 measure_amount=1 measure_type="porção" food_group="Proteína" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Salmão" calories=229.00 proteins=26.10 lipids=14.50 carbohydrates=0.00 measure_amount=1 measure_type="porção" food_group="Proteína" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Sardinha" calories=285.00 proteins=15.90 lipids=24.00 carbohydrates=0.00 measure_amount=1 measure_type="lata" food_group="Proteína" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Carne bovina" calories=153.00 proteins=30.00 lipids=2.40 carbohydrates=0.00 measure_amount=1 measure_type="porção" food_group="Proteína" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Frango" calories=212.00 proteins=33.40 lipids=7.60 carbohydrates=0.00 measure_amount=1 measure_type="porção" food_group="Proteína" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Ovo Galinha" calories=146.00 proteins=13.30 lipids=9.50 carbohydrates=0.60 measure_amount=2 measure_type="und" food_group="Proteína" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Ovo Codorna" calories=177.00 proteins=13.70 lipids=12.70 carbohydrates=0.60 measure_amount=10 measure_type="und" food_group="Proteína" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Whey" calories=396.00 proteins=66.60 lipids=6.60 carbohydrates=17.60 measure_amount=3 measure_type="scoop" food_group="Proteína" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Isocrisp Vegan" calories=108.00 proteins=15.00 lipids=1.90 carbohydrates=7.80 measure_amount=1 measure_type="scoop" food_group="Proteína" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Isocrisp Whey" calories=112.00 proteins=16.00 lipids=0.00 carbohydrates=12.00 measure_amount=1 measure_type="scoop" food_group="Proteína" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="VEGAN HARTS" calories=266.00 proteins=20.00 lipids=12.00 carbohydrates=22.00 measure_amount=1 measure_type="und" food_group="Proteína" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="CLEARPRO BAR - Nutrify" calories=134.00 proteins=16.00 lipids=5.50 carbohydrates=6.70 measure_amount=1 measure_type="und" food_group="Proteína" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="VEGANPRO BAR - Nutrify" calories=104.00 proteins=13.00 lipids=4.80 carbohydrates=4.50 measure_amount=1 measure_type="und" food_group="Proteína" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Iogurte natural" calories=126.00 proteins=6.80 lipids=7.00 carbohydrates=9.10 measure_amount=1 measure_type="und" food_group="Leite e derivados" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Queijo minas frescal" calories=214.50 proteins=15.51 lipids=15.84 carbohydrates=2.31 measure_amount=3 measure_type="fatia" food_group="Leite e derivados" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Queijo mussarela" calories=312.50 proteins=22.75 lipids=15.75 carbohydrates=0.00 measure_amount=9 measure_type="fatias"" "  meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Leite integral" calories=59.50 proteins=3.10 lipids=3.00 carbohydrates=5.00 measure_amount=1 measure_type="xicara" food_group="Leite e derivados" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Leite integral - em pó" calories=516.00 proteins=26.40 lipids=28.40 carbohydrates=38.40 measure_amount=8 measure_type="colheres de sopa" food_group="Leite e derivados" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Iogurte Yourgus (0 lactose)" calories=80.00 proteins=14.00 lipids=6.00 carbohydrates=6.00 measure_amount=1 measure_type="pote"" "  meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Iogurte Yourgus - grego" calories=103.00 proteins=14.00 lipids=2.60 carbohydrates=6.00 measure_amount=1 measure_type="pote"" "  meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Iogurte Yourgus ultra" calories=160.00 proteins=16.00 lipids=0.00 carbohydrates=22.00 measure_amount=1 measure_type="und"" "  meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Iogurte Natural MOO" calories=122.00 proteins=15.00 lipids=6.00 carbohydrates=4.00 measure_amount=1 measure_type="und"" "  meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Queijo Cottage" calories=98.00 proteins=11.00 lipids=4.30 carbohydrates=3.40 measure_amount=3 measure_type="colheres de sopa" food_group="Leite e derivados" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Abóora Italina" calories=15.00 proteins=1.10 lipids=0.20 carbohydrates=3.00 measure_amount=3 measure_type="colher de sopa" food_group="Verduras e Legumes" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Berinjela" calories=19.00 proteins=0.70 lipids=0.10 carbohydrates=4.50 measure_amount=4 measure_type="colher de sopa" food_group="Verduras e Legumes" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Beterraba" calories=32.00 proteins=1.30 lipids=0.10 carbohydrates=7.20 measure_amount=6 measure_type="colher de sopa" food_group="Verduras e Legumes" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Brócolis" calories=25.00 proteins=2.10 lipids=0.50 carbohydrates=4.40 measure_amount=1 measure_type="colher de servir" food_group="Verduras e Legumes" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Cenoura" calories=34.00 proteins=1.30 lipids=0.20 carbohydrates=7.70 measure_amount=6 measure_type="colheres de sopa" food_group="Verduras e Legumes" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Chuchu" calories=19.00 proteins=0.70 lipids=0.10 carbohydrates=4.10 measure_amount=1 measure_type="colher de servir" food_group="Verduras e Legumes" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Couve Manteiga" calories=90.00 proteins=1.70 lipids=6.60 carbohydrates=8.70 measure_amount=2 measure_type="colheres de servir" food_group="Verduras e Legumes" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Couve flor" calories=19.00 proteins=1.20 lipids=0.30 carbohydrates=3.90 measure_amount=1 measure_type="colher de servir" food_group="Verduras e Legumes" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Palmito" calories=29.00 proteins=2.50 lipids=0.50 carbohydrates=5.50 measure_amount=2 measure_type="und" food_group="Verduras e Legumes" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Pepino" calories=10.00 proteins=0.90 lipids=0.00 carbohydrates=2.00 measure_amount=9 measure_type="colher de sopa" food_group="Verduras e Legumes" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Repolho" calories=17.00 proteins=0.90 lipids=0.10 carbohydrates=3.90 measure_amount=2 measure_type="colher de servir" food_group="Verduras e Legumes" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Tomate" calories=15.00 proteins=1.10 lipids=0.20 carbohydrates=3.10 measure_amount=9 measure_type="fatias" food_group="Verduras e Legumes" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Vagem" calories=25.00 proteins=1.80 lipids=0.72 carbohydrates=5.30 measure_amount=1 measure_type="colher de servir" food_group="Verduras e Legumes" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Batata doce" calories=77.00 proteins=0.60 lipids=0.10 carbohydrates=18.40 measure_amount=3 measure_type="fatias médias" food_group="Tuberculos e derivados" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Aipim" calories=125.00 proteins=1.00 lipids=0.30 carbohydrates=30.40 measure_amount=4 measure_type="colheres de sopa" food_group="Tuberculos e derivados" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Abócora Cabotian" calories=48.00 proteins=1.40 lipids=0.70 carbohydrates=10.80 measure_amount=4 measure_type="colheres de sopa" food_group="Tuberculos e derivados" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Batata baroa" calories=80.00 proteins=0.90 lipids=0.20 carbohydrates=15.00 measure_amount=1 measure_type="und pequena" food_group="Tuberculos e derivados" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Batata inglesa" calories=103.90 proteins=2.31 lipids=0.00 carbohydrates=23.73 measure_amount=3 measure_type="colheres de sopa" food_group="Tuberculos e derivados" measure_total_grams=100 meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Panqueca de banana" calories=204.60 proteins=10.60 lipids=12.55 carbohydrates=26.60 measure_amount=1 measure_type="und" food_group="RECEITA" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Panqueca de banana com cacau" calories=239.60 proteins=13.90 lipids=14.45 carbohydrates=28.45 measure_amount=1 measure_type="und" food_group="RECEITA" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Bolo de caneca de banana" calories=187.60 proteins=10.16 lipids=6.07 carbohydrates=36.80 measure_amount=1 measure_type="und" food_group="RECEITA" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Pão de frigideira" calories=136.30 proteins=11.00 lipids=6.87 carbohydrates=15.45 measure_amount=1 measure_type="und" food_group="RECEITA" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Crepioca" calories=133.80 proteins=6.50 lipids=4.45 carbohydrates=18.60 measure_amount=1 measure_type="und" food_group="RECEITA" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Pão de queijo de frigideira" calories=173.80 proteins=9.50 lipids=7.75 carbohydrates=18.60 measure_amount=1 measure_type="und" food_group="RECEITA" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Muffin de banana" calories=240.00 proteins=16.00 lipids=17.00 carbohydrates=44.00 measure_amount=4 measure_type="und" food_group="RECEITA" measure_total_grams=100 meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Muffin de frango" calories=264.00 proteins=32.00 lipids=12.00 carbohydrates=16.00 measure_amount=4 measure_type="und" food_group="RECEITA" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Panqueca" calories=130.80 proteins=9.50 lipids=12.45 carbohydrates=4.60 measure_amount=1 measure_type="und" food_group="RECEITA" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Chocolate amargo - 60%" calories=524.00 proteins=8.80 lipids=34.80 carbohydrates=44.00 measure_amount=4 measure_type="pedaço" food_group="Doces" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Chocolate amargo - 70%" calories=635.00 proteins=6.50 lipids=50.00 carbohydrates=40.50 measure_amount=5 measure_type="Pedaço" food_group="Doces" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Chocolate amargo - 80%" calories=616.00 proteins=11.20 lipids=52.00 carbohydrates=26.80 measure_amount=4 measure_type="pedaço" food_group="Doces" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Tomate Cereja" calories=15.00 proteins=1.10 lipids=0.20 carbohydrates=3.10 measure_amount=12 measure_type="unidades" food_group="Verduras e Legumes" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Abobrinha" calories=15.00 proteins=1.10 lipids=0.20 carbohydrates=3.00 measure_amount=1 measure_type="colher de servir"" "  meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Geleia" calories=290.00 proteins=0.00 lipids=0.00 carbohydrates=70.00 measure_amount=5 measure_type="colher de sopa" food_group="Doces e derivados" measure_total_grams=100 meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Geleia 100% Fruta" calories=155.00 proteins=0.00 lipids=0.00 carbohydrates=37.50 measure_amount=5 measure_type="colher de sopoa" food_group="Doces e derivados" measure_total_grams=100 meal_number=4
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Mel" calories=332.75 proteins=0.30 lipids=0.00 carbohydrates=75.00 measure_amount=6 measure_type="colher de sopa" food_group="Açúcar" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Melado" calories=306.50 proteins=0.00 lipids=0.00 carbohydrates=76.60 measure_amount=5 measure_type="colher de sopa" food_group="Açúcar" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Isomaltose (Palatinose)" calories=396.00 proteins=0.00 lipids=0.00 carbohydrates=100.00 measure_amount=7 measure_type="colher de sopa" food_group="Açúcar" measure_total_grams=100 meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Snack grão de bico" calories=107.00 proteins=7.00 lipids=3.10 carbohydrates=14.00 measure_amount=1 measure_type="und"" "  meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Tofu" calories=60.00 proteins=7.50 lipids=3.75 carbohydrates=1.75 measure_amount=3 measure_type="fatias"" "  meal_number=5
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Leite de castanha Caju" calories=81.00 proteins=3.00 lipids=6.60 carbohydrates=2.80 measure_amount=1  meal_number=2
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Pupunha" calories=20.00 proteins=1.00 lipids=1.00 carbohydrates=2.00 measure_amount=1  meal_number=3
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="Isofort" calories=114.00 proteins=27.00 lipids=0.00 carbohydrates=1.60 measure_amount=1 measure_type="30g"" "  meal_number=1
http localhost:8080/foods/add-new/ "Authorization: Port $1" food_name="TOPWHEY3 - MAX" calories=157.00 proteins=30.00 lipids=0.00 carbohydrates=5.10 measure_amount=1 measure_type="40g"" "  meal_number=1
